config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "products#index"

  get "up" => "rails/health#show", as: :rails_health_check

  # Produtos
  get "/products", to: "products#index", as: :products
  get "/products/new", to: "products#new", as: :new_product
  post "/products", to: "products#create"
  get "/products/:id", to: "products#show", as: :product
  get "/products/:id/edit", to: "products#edit", as: :edit_product
  patch "/products/:id", to: "products#update"
  delete "/products/:id", to: "products#destroy", as: :delete_product


  # Carrinho
  resource :cart, only: [:show] do
    post :checkout
  end

  # Itens do carrinho
  resources :order_items, only: [:create, :update, :destroy]

  resources :orders, only: [:index]

  # Payments
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  # Categorias
  resources :categories, only: [:show]

  # Ofertas
  get "/products/:product_id/offers/new", to: "offers#new", as: :new_product_offer
  post "/products/:product_id/offers", to: "offers#create", as: :product_offers
  get "/offers", to: "offers#index", as: :offers
  get "/offers/:id", to: "offers#show", as: :offer
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert flash flash-success alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert flash flash-danger alert-dismissible fade show" role="alert">
    <span><%= alert %></span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <footer class="footer bg-dark text-white py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h5>Navegação</h5>
        <ul class="list-unstyled">
          <li><%= link_to "Início", root_path, class: "footer-list" %></li>
          <li><%= link_to "Produtos", products_path, class: "footer-list" %></li>
          <li><%= link_to "Minha Conta", edit_user_registration_path, class: "footer-list" %></li>
        </ul>
      </div>

      <div class="col-md-4">
        <h5>Contato</h5>
        <ul class="list-unstyled">
          <li>Email: contato@marketplace.com</li>
          <li>Telefone: (00) 1234-5678</li>
        </ul>
      </div>

      <div class="col-md-4">
        <h5>Siga-nos</h5>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#" class="footer-icons">
              <i class="bi bi-facebook" style="font-size: 1rem;"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#" class="footer-icons">
              <i class="bi bi-instagram" style="font-size: 1rem;"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#" class="footer-icons">
              <i class="bi bi-twitter" style="font-size: 1rem;"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <hr class="bg-secondary">
    <div class="text-center text-secondary footer-copy">
      <p class="footer-copy">&copy; <%= Time.now.year %> ClosetUp. Todos os direitos reservados.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand logo" href="/">
          <%= image_tag "closetup_logo.png", alt: "ClosetUp Logo", height: 90 %>
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div class="mx-auto" style="max-width: 500px; width: 100%;">
          <form class="d-flex" role="search">
            <input class="form-control me-2 mt-2" type="search" placeholder="Buscar produtos" aria-label="Search">
            <button class="btn btn-outline-success mt-2" type="submit">
              <i class="bi bi-search"></i>
            </button>
          </form>
        </div>

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to edit_user_registration_path, class: "nav-link text-white" do %>
                <i class="bi bi-person fs-4"></i>
            <% end %>
          <li class="nav-item mt-2">
          <%= link_to cart_path, class: "nav-link text-white position-relative" do %>
            <i class="fa-solid fa-cart-shopping fs-"></i>
            <% if defined?(current_order) && current_order && current_order.order_items.any? %>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                <%= current_order.order_items.sum(:quantity) %>
              </span>
            <% end %>
          <% end %>
        </li>

            <li class="nav-item mt-2">
              <%= link_to orders_path, class: "nav-link text-white" do %>
              Olá, <%= current_user.email %>
              <% end %>
            </li>
            <li class="nav-item mt-2">
              <%= link_to "Adicionar produto", new_product_path, class: "nav-link btn-add-product" %>
            </li>
            </li>
            <li class="nav-item mt-2">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link text-white" %>
            </li>
          <% else %>
            <li class="nav-item mt-2">
              <%= link_to "Entrar", new_user_session_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item mt-2">
              <%= link_to "Criar conta", new_user_registration_path, class: "nav-link text-white" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>


  <nav class="navbar navbar-dark bg-secondary">
    <div class="container-fluid">
      <ul class="navbar-nav d-flex flex-row w-100 justify-content-between overflow-auto">
        <% Category.all.each do |category| %>
          <li class="container nav-item text-center">
            <%= link_to category_path(category), class: "nav-link text-white px-2" do %>
              <%= category.title %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>