config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "products#index"

  get "up" => "rails/health#show", as: :rails_health_check

  # Produtos
  get "/products", to: "products#index", as: :products
  get "/products/new", to: "products#new", as: :new_product
  post "/products", to: "products#create"
  get "/products/:id", to: "products#show", as: :product
  get "/products/:id/edit", to: "products#edit", as: :edit_product
  patch "/products/:id", to: "products#update"
  delete "/products/:id", to: "products#destroy", as: :delete_product


  # Carrinho
  resource :cart, only: [:show] do
    post :checkout
  end

  # Itens do carrinho
  resources :order_items, only: [:create, :update, :destroy]

  resources :orders, only: [:index]

  # Payments
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  # Categorias
  resources :categories, only: [:show]

  # Ofertas
  get "/products/:product_id/offers/new", to: "offers#new", as: :new_product_offer
  post "/products/:product_id/offers", to: "offers#create", as: :product_offers
  get "/offers", to: "offers#index", as: :offers
  get "/offers/:id", to: "offers#show", as: :offer
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :orders

  SIZES = %w[PP P M G GG XG].freeze

  monetize :price_cents

  has_many :offers, dependent: :destroy
  # has_one_attached :image
  has_many_attached :images

  validates :size, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :sku, presence: true, uniqueness: true

  include PgSearch::Model
  pg_search_scope :search_text,
                  against: { title: 'A',
                             description: 'B' },
                  associated_against: { category: :title },
                  using: { tsearch: { prefix: true } }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]

  def index
    @products = Product.all
    if params[:query].present?
      @products = Product.search_text(params[:query])
    end
    return unless params[:category_id]
    @category = Category.find_by(id: params[:category_id])
    if @category
      @products = Product.where(category: @category)
    else
      redirect_to products_path, alert: "Categoria não encontrada"
    end
  end

  def show
    @offers = @product.offers.includes(:user) if @product.respond_to?(:offers)
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = current_user.products.build(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product), notice: "Produto criado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    if @product.orders.exists?
      redirect_to product_path(@product), alert: "Não é possível deletar este produto, pois ele já tem pedidos associados."
    else
      @product.destroy
      redirect_to products_path, notice: "Produto deletado com sucesso."
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Produto atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :sku, :price, :category_id, images: [], size: [])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def authorize_user!
    unless @product.user == current_user
      redirect_to products_path, alert: "Você não está autorizado a realizar esta ação."
    end
  end

end

app/views/products/_product_card.html.erb
<div class="card h-100">
  <% if product.images.attached? %>
    <div id="product-<%= product.id %>" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner ratio ratio-4x3">
        <% product.images.each_with_index do |image, i| %>
          <div class="carousel-item <%= i.zero? ? 'active' : '' %>" data-bs-interval="<%= i.zero? ? '10000' : '2000' %>">
            <%= cl_image_tag image.key, crop: :fill, class: "d-block w-100 h-100", style: "object-fit: cover;" %>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#product-<%= product.id %>" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#product-<%= product.id %>" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Próximo</span>
      </button>
    </div>
  <% end %>

  <div class="card-body d-flex flex-column">
    <h5 class="card-title"><%= product.title %></h5>
    <p class="card-text description"><%= product.description %></p>
    <p class="card-text"><%= product.category.title %></p>

  <%= form_with url: orders_path, method: :post, local: true, class: "mt-2" do |f| %>
    <%= hidden_field_tag "order[product_id]", product.id %>

    <div class="d-flex flex-wrap gap-2 justify-content-center">
      <% sizes = Array(product.size).reject(&:blank?) %>
      <% if sizes.count == 1 %>
        <% # Caso de um único tamanho %>
        <% t = sizes.first %>
        <% rid = "p#{product.id}-size-0" %>
        <input type="radio"
                class="btn-check"
                name="order[size]"
                id="<%= rid %>"
                value="<%= t %>"
                autocomplete="off"
                required
                checked>
        <label class="btn btn-outline-dark btn-sm" for="<%= rid %>"><%= t %></label>
      <% else %>
        <% # Caso de múltiplos tamanhos %>
        <% sizes.each_with_index do |t, i| %>
          <% rid = "p#{product.id}-size-#{i}" %>
          <input type="radio"
                class="btn-check"
                name="order[size]"
                id="<%= rid %>"
                value="<%= t %>"
                autocomplete="off"
                required>
          <label class="btn btn-outline-dark btn-sm" for="<%= rid %>"><%= t %></label>
        <% end %>
      <% end %>
    </div>
  <% end %>
    <p class="card-text"><strong><%= humanized_money_with_symbol(product.price) %></strong></p>
    <%= link_to "Ver produto", product_path(product), class: "btn-view-product" %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container mt-5">
  <h1>Edit a product</h1>

  <%= simple_form_for @product do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :sku %>
    <%= f.input :price %>
    <%= f.input :category_id, collection: @categories, prompt: "Selecione uma categoria" %>
    <%= f.input :image, as: :file, label: "Imagem do Produto" %>

    <%= f.button :submit, "Atualizar produto", class: "btn-product-update" %>
  <% end %>
</div>

</div>

app/views/products/index.html.erb
<div class="banner position-relative d-flex align-items-center justify-content-center text-center text-white">
  <div class="container py-5">
    <h1 class="display-4 fw-bold mb-3">ClosetUp: Seu Estilo, Elevado</h1>
    <p class="lead mb-4">
      Descubra as últimas tendências e peças essenciais para o seu guarda-roupa. <br>
      Nossa coleção exclusiva de roupas e acessórios foi cuidadosamente selecionada para refletir o seu estilo único.
    </p>
    <%= link_to "Comprar agora", '#products', class: "btn btn-outline-light btn-lg" %>
  </div>
</div>

<div id="products" class="container mt-4">
  <h1 class="mt-4 mb-4">Todos os produtos</h1>
  <div class="row g-4">
    <% @products.each do |product| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card h-100">
          <% if product.images.attached? %>
            <div id="product-<%= product.id %>" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner ratio ratio-4x3">
                <% product.images.each_with_index do |image, i| %>
                  <div class="carousel-item <%= i.zero? ? 'active' : '' %>" data-bs-interval="<%= i.zero? ? '10000' : '2000' %>">
                    <%= cl_image_tag image.key, crop: :fill, class: "d-block w-100 h-100", style: "object-fit: cover;" %>
                  </div>
                <% end %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#product-<%= product.id %>" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Anterior</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#product-<%= product.id %>" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Próximo</span>
              </button>
            </div>
          <% end %>

          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= product.title %></h5>
            <p class="card-text description"><%= product.description %></p>
            <p class="card-text"><%= product.category.title %></p>

          <%= form_with url: orders_path, method: :post, local: true, class: "mt-2" do |f| %>
            <%= hidden_field_tag "order[product_id]", product.id %>

            <div class="d-flex flex-wrap gap-2 justify-content-center">
              <% sizes = Array(product.size).reject(&:blank?) %>
              <% if sizes.count == 1 %>
                <% # Caso de um único tamanho %>
                <% t = sizes.first %>
                <% rid = "p#{product.id}-size-0" %>
                <input type="radio"
                        class="btn-check"
                        name="order[size]"
                        id="<%= rid %>"
                        value="<%= t %>"
                        autocomplete="off"
                        required
                        checked>
                <label class="btn btn-outline-dark btn-sm" for="<%= rid %>"><%= t %></label>
              <% else %>
                <% sizes.each_with_index do |t, i| %>
                  <% rid = "p#{product.id}-size-#{i}" %>
                  <input type="radio"
                        class="btn-check"
                        name="order[size]"
                        id="<%= rid %>"
                        value="<%= t %>"
                        autocomplete="off"
                        required>
                  <label class="btn btn-outline-dark btn-sm" for="<%= rid %>"><%= t %></label>
                <% end %>
              <% end %>
            </div>
          <% end %>
            <p class="card-text"><strong><%= humanized_money_with_symbol(product.price) %></strong></p>
            <%= link_to "Ver produto", product_path(product), class: "btn-view-product" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1 class="add-new-product">Adicione um novo produto</h1>

  <%= simple_form_for @product do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :sku %>
    <%= f.input :price %>
    <%= f.input :category_id, collection: @categories, prompt: "Selecione uma categoria" %>
    <%= f.input :size,
                as: :check_boxes,
                collection: Product::SIZES,
                label: "Tamanhos disponíveis" %>
    <%= f.input :images, as: :file, input_html: { multiple: true, direct_upload: true, accept: "image/*" }, label: "Imagens do Produto" %>

    <%= f.button :submit, "Criar Produto", class: "btn-create-product" %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container product-show">
  <div class="product-image-container">
    <div class="card h-100">
      <div id="carouselExampleRide-<%= @product.id %>" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% @product.images.each_with_index do |image, i| %>
            <div class="carousel-item <%= 'active' if i.zero? %>">
              <%= cl_image_tag image.key, class: "d-block w-100", alt: @product.title, transformation: { width: 600, height: 400, crop: :limit } %>
            </div>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button"
                data-bs-target="#carouselExampleRide-<%= @product.id %>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button"
                data-bs-target="#carouselExampleRide-<%= @product.id %>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Próximo</span>
        </button>
      </div>
    </div>
  </div>

  <div class="product-details-container ms-4 flex-grow-1">
    <h1><%= @product.title %></h1>

    <div class="accordion" id="productAccordion">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseDescription" aria-expanded="true" aria-controls="collapseDescription">
            Descrição
          </button>
        </h2>
        <div id="collapseDescription" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#productAccordion">
          <div class="accordion-body">
            <%= @product.description %>
          </div>
        </div>
      </div>
    </div>

    <p>
      <div class="product-price"><%= humanized_money_with_symbol(@product.price) %></div>
    </p>

    <%= form_with url: order_items_path, method: :post, local: true, class: "mb-4" do |f| %>
    <%= hidden_field_tag :product_id, @product.id %>

      <p>Tamanhos disponíveis: </p>
    <div class="d-flex flex-wrap gap-2 mb-4">
      <% sizes = Array(@product.size).reject(&:blank?) %>
      <% if sizes.count == 1 %>
        <% t = sizes.first %>
        <% rid = "p#{@product.id}-size-0" %>
        <input type="radio"
                class="btn-check"
                name="size"
                id="<%= rid %>"
                value="<%= t %>"
                autocomplete="off"
                required
                checked>
        <label class="btn btn-outline-dark btn-sm" for="<%= rid %>"><%= t %></label>
      <% else %>
          <% sizes.each_with_index do |t, i| %>
          <% rid = "p#{@product.id}-size-#{i}" %>
          <input type="radio"
                class="btn-check"
                name="size"
                id="<%= rid %>"
                value="<%= t %>"
                autocomplete="off"
                required>
          <label class="btn btn-outline-dark btn-sm" for="<%= rid %>"><%= t %></label>
        <% end %>

      <% end %>
    </div>

    <div class="mb-3" style="max-width: 160px;">
      <label for="quantity" class="form-label">Quantidade</label>
      <%= number_field_tag :quantity, 1, min: 1, step: 1, class: "form-control", id: "quantity" %>
    </div>

    <% if @product.user == current_user %>
      <%= link_to 'Editar', edit_product_path(@product), class: 'btn-edit' %>

      <button type="button" class="btn-delete" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">
        Deletar
      </button>

      <%= link_to 'Retornar para produtos', products_path, class: 'btn-return-to-products' %>
    <% else %>

      <%= submit_tag 'Adicionar ao carrinho', class: 'btn-buy-product' %>
      <%= link_to 'Retornar para produtos', products_path, class: 'btn-return-to-products' %>
    <% end %>
    <% end %>

    <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirmação de exclusão</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Tem certeza que deseja deletar este produto? Esta ação não pode ser desfeita.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <%= link_to 'Deletar', product_path(@product), data: { turbo_method: :delete }, class: 'btn-delete' %>
          </div>
        </div>
      </div>
    </div>

    <p class="product-last-details">
      <%= "Category #{@product.category.title}" %>
    </p>
    <p class="product-last-details">
      <%= "SKU: #{@product.sku}" %>
    </p>
    <p class="product-last-details">
      <%= "Created at: #{@product.created_at.strftime("%B %d, %Y")}"%>
    </p>
    <p class="product-last-details">
      <%= "Updated at: #{@product.updated_at.strftime("%B %d, %Y")}" %>
    </p>
  </div>
</div>